In [2]:
import numpy as np
import matplotlib.pyplot as plt
import random
import datetime

In [16]:
new_arr = np.array([2,3,4,5,6])
new_arr
end = datetime.datetime.now()
duration = end - start
print(duration.seconds)

NameError: name 'datetime' is not defined

In [5]:
print(type(new_arr))

<class 'numpy.ndarray'>


In [6]:
z = [1,2,3,4]
#z-3
z*2

[1, 2, 3, 4, 1, 2, 3, 4]

In [7]:
np_z = np.array(z)
np_z *2

array([2, 4, 6, 8])

In [8]:
mean_np_z = np_z.mean()
mean_np_z

2.5

In [13]:
x = [2,5,10,3,5,5,2,7] 
newlist = []
for num in x :
    xy = num*0.5
    print(xy)
    newlist.append(xy)
print(newlist)
    

1.0
2.5
5.0
1.5
2.5
2.5
1.0
3.5
[1.0, 2.5, 5.0, 1.5, 2.5, 2.5, 1.0, 3.5]


In [14]:
x =[2,5,10,3,5,5,2,7]* 100000
 

In [17]:
np_x = np.ones(10000)
np_x.mean()

1.0

In [18]:
data = np.array([1,2,3,4,5,6,7] * (4*12*2))
data.shape

(672,)

In [25]:
vals=data.reshape([24,4,7])

In [26]:
vals[0]

array([[1, 2, 3, 4, 5, 6, 7],
       [1, 2, 3, 4, 5, 6, 7],
       [1, 2, 3, 4, 5, 6, 7],
       [1, 2, 3, 4, 5, 6, 7]])

In [37]:
students_scores = np.random.randint(low=0,high=100,size = 60)
print(list(students_scores))

[46, 47, 62, 59, 76, 44, 11, 12, 1, 20, 81, 41, 74, 36, 84, 2, 7, 8, 64, 84, 11, 61, 7, 38, 64, 27, 63, 3, 9, 1, 12, 7, 92, 7, 34, 8, 96, 69, 96, 26, 75, 79, 55, 3, 15, 70, 63, 61, 99, 40, 8, 88, 33, 77, 66, 50, 90, 97, 19, 36]


In [38]:
students_scores[students_scores > 50] #boolean mask

array([62, 59, 76, 81, 74, 84, 64, 84, 61, 64, 63, 92, 96, 69, 96, 75, 79,
       55, 70, 63, 61, 99, 88, 77, 66, 90, 97])

In [39]:
len(students_scores[students_scores > 50])

27

In [ ]:
z = np.linspace(2,20)